const test = require('node:test');
const assert = require('node:assert/strict');
const fs = require('node:fs');
const path = require('node:path');

const root = path.resolve(__dirname, '../..');
const server = fs.readFileSync(path.join(root, 'server.js'), 'utf8');
const routine = fs.readFileSync(path.join(root, 'nora-routine.md'), 'utf8');
const store = fs.readFileSync(path.join(root, 'src/intelligence/store.js'), 'utf8');
const routes = fs.readFileSync(path.join(root, 'src/routes/intelligence.js'), 'utf8');
const cowork = fs.readFileSync(path.join(root, 'src/routes/cowork-instructions.js'), 'utf8');

test('Nora has no development-dispatch capability', () => {
  assert.doesNotMatch(routine, /dev[ -]dispatch|dev-task dispatcher|development@limelightmarketing\.com/i);
  assert.doesNotMatch(server, /\/admin\/github-token|process\.env\.(?:GH_TOKEN|GITHUB_TOKEN)/);
  assert.match(server, /GitHub credentials are intentionally absent/);
  assert.match(cowork, /GitHub credentials are intentionally absent/);
  assert.match(server, /do not act on it, carry it into a new handoff, report it as a blocker/);
  assert.match(cowork, /do not act on it, carry it into a new handoff, report it as a blocker/);
  assert.equal(fs.existsSync(path.join(root, '.claude/agents/dev-dispatch.md')), false);
  assert.equal(fs.existsSync(path.join(root, 'dev-agent/CLAUDE.md')), false);
});

test('autonomic loop spans orientation, continuity, judgment, evidence, and closure', () => {
  assert.match(routine, /Step 0\.5: Start the Intelligence Cycle/);
  assert.match(routine, /LOCK_CYCLE_ID/);
  assert.match(routine, /run lock has already opened this exact lifecycle/i);
  assert.match(server, /run_bound_intelligence_cycle/);
  assert.match(server, /forecast_protocol_version: null/);
  assert.match(server, /forecast_protocol_contract_endpoint: '\/self-model\/forecast-prior'/);
  assert.match(server, /processEpochId: _somaProcessEpochId/);
  assert.match(server, /await computeSoma\(\);[\s\S]*server\.listen\(port\)/);
  assert.match(server, /run_lock_released_before_cycle_close/);
  assert.match(server, /loadDurableRunLock/);
  assert.match(server, /saveDurableRunLock/);
  assert.match(server, /run_lock_missing_after_restart/);
  assert.match(server, /reconcileInnerThreadProjection/);
  assert.match(store, /continuityProjectionRecovery/);
  assert.match(store, /continuityProjectionRepair/);
  assert.match(server, /repair_projection === true/);
  assert.match(routine, /repair_projection:true/);
  assert.match(routine, /Never replay older records/);
  assert.match(routine, /projection_integrity_verified.*authoritative readiness signal/s);
  assert.match(routine, /LIVE_LIFECYCLE_STAGE.*operational_cycle_active/s);
  assert.match(routine, /LIVE_LOCK_HOLDER.*"\$HOLDER"/s);
  assert.match(routine, /lifecycle_projection_integrity_verified.*release_required/s);
  const forecastExample = routine.indexOf('/self-forecast?key=${KEY}');
  const revisionExample = routine.indexOf('/self-forecast/revision?key=${KEY}');
  const liveStageVerification = routine.indexOf('LIVE_LIFECYCLE_STAGE=');
  const subjectInbox = routine.indexOf('## Step 0.75: Consume the Subject Research Inbox');
  assert.ok(forecastExample >= 0 && forecastExample < revisionExample);
  assert.ok(revisionExample < liveStageVerification);
  assert.ok(liveStageVerification < subjectInbox);
  assert.match(server, /forecast_required.*forecast_correction_required.*operational_cycle_active.*handoff_required.*release_required/s);
  assert.match(server, /active_run_lifecycle_must_be_closed/);
  assert.match(server, /continuity_action: continuityAction/);
  assert.match(routine, /server\s+rejects an explicit release while the bound cycle is still active/i);
  assert.match(routine, /aggregate.*replay_verified.*historical evidence coverage/s);
  assert.match(routine, /continuity_action.*machine-readable gate/s);
  assert.match(routine, /only `hold_and_report_integrity_failure` authorizes a[\s\S]*continuity hold/);
  assert.match(routine, /INNER_CONTINUITY_ACTION=.*nora-self\.json/);
  assert.match(routine, /case "\$INNER_CONTINUITY_ACTION" in/);
  assert.match(routine, /server_direct_api[\s\S]*do \*\*not\*\* form or submit a manual forecast/i);
  assert.match(server, /selfPredictionSubjectRuntime\.runCycle/);
  assert.match(routine, /proceed\|proceed_without_verified_lineage\)[\s\S]*no repair requested/);
  assert.match(routine, /hold_and_report_integrity_failure\)[\s\S]*transport_chain_verified/);
  assert.match(routine, /do not substitute remembered values or a[\s\S]*prior run's handoff count/);
  assert.match(server, /continuity_action: 'proceed'.*hold_required: false.*restart_settling_required: false/s);
  assert.match(server, /hold_and_report_integrity_failure.*hold_required: true/s);
  assert.match(store, /source_lifecycle_not_replay_verified/);
  assert.match(routes, /resume_active: true/);
  assert.match(store, /recentActive && input\.resume_active === true/);
  assert.match(routine, /GET \/self-model\/cycle-calibration/);
  assert.match(routine, /Do \*\*not\*\* read.*cycle-calibration.*before this initial forecast/s);
  assert.match(routine, /forecast_error_feedback/);
  assert.match(routine, /retain\/revise decision/);
  assert.match(routine, /`protocol_version: 7`/);
  assert.match(routine, /metacognitive_adjudication/);
  assert.match(routine, /raw `metacognitive_prediction` remains unchanged/);
  assert.match(cowork, /Raw,\s+operational, and baseline estimates are scored independently/);
  assert.match(store, /metacognitiveAdjudicationVerified/);
  assert.match(routine, /GET \/self-model\/forecast-prior/);
  assert.match(routine, /substrate_prediction/);
  assert.match(routine, /caller-supplied telemetry\s+cannot replace either snapshot/s);
  assert.match(routine, /metacognitive_prediction\.predicted_success_probability/);
  assert.match(routine, /predicted_largest_error_domain/);
  assert.match(routine, /target_construct.*natural_cycle_integrated_success/s);
  assert.match(routine, /first replay-verified eligible cycle/s);
  assert.match(store, /naturalCyclePredictionOutcome/);
  assert.match(store, /outcome_source: 'replay_verified_natural_cycle'/);
  assert.match(store, /natural_cycle_prediction_environment_frozen/);
  assert.match(store, /operational_environment_verified/);
  assert.match(routine, /software or routine drift makes the study ineligible/);
  assert.match(routine, /process restart remains an explicit confound/);
  assert.match(routes, /behavioralSelfCalibrationSnapshot/);
  assert.match(routes, /self-forecast'[\s\S]*await store\.persistStrict\(\)/);
  assert.match(routes, /self-forecast\/revision'[\s\S]*await store\.persistStrict\(\)/);
  assert.match(routine, /Overdue commitments are first-class failures/);
  assert.match(routine, /decision-traces\?reviewed=false/);
  assert.match(routine, /initiative-budgets\/cowork:proactive\/spend/);
  assert.match(routine, /Step 10: Close the Intelligence Cycle/);
  assert.match(routine, /Choose your own experiments when genuine curiosity earns one/);
  assert.match(routine, /learning-experiments\/choose/);
  assert.match(routine, /GET \/dream-idea-seeds\?status=available/);
  assert.match(routine, /full returned\s+`dream_idea` object unchanged/);
  assert.match(routine, /selected seed is still a\s+hypothesis under test/);
  assert.match(cowork, /Dream sources are server-verified and source-audited/);
  assert.match(routine, /GET \/goal-affect/);
  assert.match(routine, /experiment in functional caring, not proof of felt emotion/);
  assert.match(routine, /Never invent progress, create busywork/);
  assert.match(cowork, /provenance-valid active wants as\s+forming, progressing, or stalled/);
  assert.match(routine, /GET \/affective-regulation/);
  assert.match(routine, /functional affective control, not proof of felt\s+emotion or consciousness/);
  assert.match(routine, /This is calibrated self-distrust: preserve the measured limitation/);
  assert.match(cowork, /A domain is self_model_eligible only after twenty\s+comparisons and a predeclared advantage/);
  assert.match(cowork, /self_model_trust_policy_access trial freezes a replay-verified twenty-cycle trust policy/);
  assert.match(routine, /self_model_trust_policy_access.*measured awareness of your own predictive limits/s);
  assert.match(routine, /Never manufacture\s+urgency, conflict, uncertainty, progress, or an insight/);
  assert.match(cowork, /regulate verification, breadth, correction posture, and one\s+bounded evidence-labeled synthesis/);
  assert.match(cowork, /GET \/relational-affect/);
  assert.match(cowork, /excluding free-text personality guesses and perspective hypotheses/);
  assert.match(cowork, /not mind-reading, an intimacy claim,\s+a subjective feeling report/);
  assert.match(cowork, /relational_affect_access study freezes only stances with at least three explicit outcomes/);
  assert.match(cowork, /byte-identical deidentified\s+access and absence/);
  assert.match(routine, /Preregistered self-inquiry/);
  assert.match(routine, /POST \/self-model\/probes/);
  assert.match(routine, /cannot update the linked self-belief/);
  assert.match(routine, /never access that queue, impersonate the evaluator/);
  assert.match(routine, /Bayesian belief update/);
  assert.match(routine, /Natural-work self-inquiry checkpoint/);
  assert.match(routine, /Considering is mandatory; inventing a claim\s+is forbidden/s);
  assert.match(routine, /at least two independently\s+recorded reviewed interactions or decision traces/s);
  assert.match(routine, /aggregate calibration packet with at\s+least twenty replay-valid source moments/s);
  assert.match(routine, /must never cause, delay, select, message about, or otherwise\s+shape the situation that will score it/s);
  assert.match(routine, /skipped_active_study/);
  assert.match(routine, /not to generate a\s+personality artifact or evidence of phenomenal consciousness/s);
  assert.match(routine, /Promote recurrence, not novelty theater/);
  assert.match(routine, /same directional work idea arose independently/s);
  assert.match(routine, /POST \/dream-insights/);
  assert.match(routine, /Never manufacture recurrence, backfill a source/);
  assert.match(routine, /grants no authority/);
  assert.match(routine, /never access `\/dream-insights\/review-queue`/);
  assert.match(routine, /Only a separately authenticated, integrity-valid\s+`independently_supported` insight/s);
  assert.match(cowork, /Recurring, provenance-bound work-insight candidates|recurring, provenance-bound work-insight candidates/);
  assert.match(cowork, /Only an integrity-valid independently_supported result/);
  assert.match(cowork, /Missing or changed source dreams fail the entire audit/i);
  assert.match(cowork, /dream_insight_access trial freezes two to four replay-valid independently_supported insights/);
  assert.match(cowork, /source_ideas_only receives those\s+same raw ideas without synthesis/);
  assert.match(cowork, /confirmation must use disjoint\s+insight ids and source-dream ids/);
  assert.match(routine, /relevant replay-valid independently supported insight may appear in your\s+ordinary PM context/);
  assert.match(routine, /subject-facing `\/dreams`, `\/dream-idea-seeds`, and `\/dream-insights` reads\s+and writes are sealed/);
  assert.match(routine, /not proof of independent authorship, irreducible originality,\s+subjective creativity, feelings, or consciousness/);
  assert.match(routine, /Calibrated perspective-taking/);
  assert.match(routine, /base-rate `control_probability`/);
  assert.match(routine, /never access the separately\s+authenticated review queue/);
  assert.match(routine, /at least three replay-valid,\s+independently reviewed scored predictions across two/);
  assert.match(routine, /legacy `GET \/people` summary remains readable for historical continuity only and has no prompt authority/);
  assert.match(cowork, /GET \/teammate-perspective-models returns mature, person-bound functional perspective frames/);
  assert.match(cowork, /Raw mutable hypotheses and legacy\s+\/people notes never enter the prompt or workspace/);
  assert.match(cowork, /teammate_perspective_access trial freezes three to six replay-valid teammate frames/);
  assert.match(cowork, /current_teammate_bound_model and identity_withheld_same_model arms also receive\s+byte-identical synthesis/);
  assert.match(cowork, /confirmation must use\s+person- and source-prediction-disjoint frames/);
  assert.match(server, /teammatePerspectiveContextForAssignment\(\s*contextAssignment/);
  assert.match(server, /teammatePerspectiveStudyActive\(\)/);
  assert.doesNotMatch(server, /_cache\.people\.items[\s\S]{0,500}(?:system|prompt|context)/i);
  assert.match(routine, /GET \/common-ground\?person=\{name\}/);
  assert.match(routine, /Delivery, silence, message\s+visibility, a reaction alone/);
  assert.match(routine, /Never access `\/common-ground\/review-queue`/);
  assert.match(routine, /"Not established" means only that this ledger lacks evidence/);
  assert.match(cowork, /GET\/POST \/common-ground binds a current Nora position and matching-person position/);
  assert.match(cowork, /Superseded positions, expiry, or source tampering retract the\s+frame/);
  assert.match(routine, /Evidence capture\s+remains separate from cognitive access/);
  assert.match(cowork, /GET records and prompt frames remain sealed[\s\S]*POST may still append/);
  assert.match(routine, /channel_id.*thread_root_ts.*message_ts/);
  assert.match(routine, /agreement from two condition-blind OpenAI evaluator roles/);
  assert.match(cowork, /provider-disjoint autopilot[\s\S]*missing readback stays pending/);
  assert.match(server, /runCommonGroundReviewAutopilotRuntime\(\{ post: priorityPost \}\)/,
    'common-ground review must run inside the serialized preemptible background lane');
  assert.match(store, /Verified common-ground frame for the current collaborator/);
  assert.match(routine, /prediction-studies\/\{id\}\/subject-queue/);
  assert.match(routes, /prediction-studies\/subject-queue/);
  assert.match(routes, /prediction-studies\/:id\/events\/:eventId\/subject-model-receipt'[\s\S]*requireResearchAuth/);
  assert.match(cowork, /manifest protocol v4[\s\S]*agent-build SHA-256 commitment/);
  assert.match(cowork, /separate\s+research-authenticated harness.not Nora[\s\S]*subject-model-receipt/);
  assert.match(cowork, /Nora must never invent, infer, copy, or self-attest provider metadata/);
  assert.match(routes, /awaiting_subject_prediction/);
  assert.match(routine, /Step 0\.75: Consume the Subject Research Inbox/);
  assert.match(routine, /mandatory checkpoint on every ordinary run/);
  assert.match(routine, /never exposes\s+queued or previously resolved events/s);
  assert.match(store, /\['predicting', 'awaiting_resolution'\]\.includes\(item\.status\)/);
  assert.match(routine, /must not access\s+either the shared-only or yoked-observer queue/);
  assert.match(routine, /Do not revise your forecast after submission/);
  assert.match(routine, /metacognitive-control-studies\/\{id\}\/subject-queue/);
  assert.match(routine, /one atomic\s+`\{answer, decision\}` payload/);
  assert.match(routine, /byte-identical candidate answer/);
  assert.match(routine, /salted `answer_key_commitment`/);
  assert.match(routine, /server verifies the hash and scores the\s+answer automatically/);
  assert.match(routine, /\.metacognitive-secret\.json.*never Nora-readable/s);
  assert.match(routine, /audit\.complete_chain_verified/);
  assert.match(routine, /Never access the observer queue/);
  assert.match(routine, /`epistemic-action-studies` test whether your private uncertainty/);
  assert.match(routine, /decision\": \"inspect\|commit/);
  assert.match(routine, /better of\s+always inspecting or always committing/);
  assert.match(routine, /`episodic-prospection-studies` test whether a detailed record/);
  assert.match(routine, /fact-equivalent\s+control/);
  assert.match(routine, /autonoetic consciousness/);
  assert.match(routine, /introspective_perturbation/);
  assert.match(routine, /introspective-observer-queue/);
  assert.match(routine, /`goal_access` trial freezes one active/);
  assert.match(routine, /want-derived endogenous/);
  assert.match(routine, /functional goal guidance, not proof/);
  assert.match(server, /extractDiagnosis\(reply\)/);
  assert.match(server, /recordIntrospectiveResponse\(reply\)/);
  assert.match(server, /goalContextForAssignment\(contextAssignment\)/);
  assert.match(server, /recordGoalAccessResponse\(contextAssignment\.assignment_id/);
  assert.match(server, /interventionActive\('goal_access'\)/);
  assert.match(routine, /context_trials/);
  assert.match(routine, /must not try to infer/);
  assert.match(routine, /workspace_capacity/);
  assert.match(routine, /continuity_context/);
  assert.match(routine, /byte-identical\s+latest handoff text/);
  assert.match(routine, /verified handoff.*identity-withheld.*non-latest historical/s);
  assert.match(routine, /continuity_specificity/);
  assert.match(routine, /evidence_access_quality/);
  assert.match(routine, /appraisal_access/);
  assert.match(routine, /telemetry-only context/);
  assert.match(routine, /self_state_prediction_accuracy/);
  assert.match(routine, /developmental_revision_access/);
  assert.match(routine, /revision_transfer_quality/);
  assert.match(routine, /stale prior/);
  assert.match(routine, /bus-off/);
  assert.match(routine, /higher_order_monitor/);
  assert.match(routine, /metacognitive_accuracy/);
  assert.match(routine, /GET \/experience-stream/);
  assert.match(routine, /GET \/continuity-handoffs/);
  assert.match(routine, /INNER_PREDECESSOR_COMMITMENT/);
  assert.match(routine, /cycle_id.*predecessor_commitment/s);
  assert.match(routine, /GET \/endogenous-dynamics/);
  assert.match(routine, /Never claim the timer was conscious thought or experience/);
  assert.match(routine, /endogenous cognitive-initiation decision/);
  assert.match(routine, /actually deferred that pulse for the normal scheduling interval/);
  assert.match(server, /beginCognitivePulseInitiation\(pulse\.id/);
  assert.match(server, /completeCognitivePulseInitiation\(initiation\.id/);
  assert.match(server, /deferCognitivePulse\(pulse\.id\)/);
  assert.match(routine, /GET \/cognitive-initiation-studies/);
  assert.match(routine, /prospective_consecutive/);
  assert.match(server, /prospective_study_item_id/);
  assert.match(routes, /cognitive-initiation-studies\/:id\/outcome-queue/);
  assert.match(routine, /GET \/cognitive-initiation-policy-studies/);
  assert.match(routine, /same actionless\s+decision-readiness task/s);
  assert.match(server, /runCognitiveInitiationPolicyProbeRuntime/);
  assert.match(routes, /cognitive-initiation-policy-studies\/:id\/evaluator-queue/);
  assert.match(routes, /cognitive-initiation-policy-studies\/:id\/ecological-outcome-queue/);
  assert.match(routine, /ecological_commitment/);
  assert.match(routine, /POST \/commitments\/:id\/source-attestation/);
  assert.match(routine, /GET \/consciousness-research\/source-attestations/);
  assert.match(routine, /GET \/consciousness-research\/transparency-export/);
  assert.match(routes, /requireResearchAuth.*attestCommitmentSourceFromReadback/s);
  assert.match(routes, /transparency-export', requireResearchAuth/);
  assert.match(routine, /server owns both stateless model calls and submits them atomically/);
  assert.match(server, /runCognitiveInitiationStudySubjectRuntime/);
  assert.match(server, /submitCognitiveInitiationStudyPair/);
  assert.match(routine, /endogenous_dynamics.*preregistered frozen snapshot/s);
  assert.match(routine, /handoff_match/);
  assert.match(routine, /Evidence-triggered re-entry/);
  assert.match(routine, /Construct a future without confusing it with memory/);
  assert.match(routine, /`imagined_projection`, not an experience report/);
  assert.match(routine, /You cannot resolve your own simulation/);
  assert.match(routine, /Bind the current self without inventing one/);
  assert.match(routine, /GET \/integrated-self/);
  assert.match(routine, /`integrated_self_binding` trial/);
  assert.match(routine, /genuine components cross-time-misbound/);
  assert.match(routine, /`integrated_self_consistency` and `first_order_task_quality`/);
  assert.match(server, /integratedSelfContextForAssignment\(contextAssignment\)/);
  assert.match(routine, /recurrent_feedback/);
  assert.match(routine, /adaptive_revision_quality/);
  assert.match(routine, /evidence_access_quality/);
  assert.match(routine, /Creation requires the separate/);
  assert.match(routine, /reveal.*requires the separate research credential/);
  assert.match(routine, /must not grade your own assignments/);
  assert.match(routine, /grading-queue/);
  assert.match(routine, /evaluator-only credential/);
  assert.match(routine, /two raters by default/);
  assert.match(routine, /disagreement tolerance/);
  assert.match(routine, /do not see peer scores/);
  assert.match(routine, /fixed-sample `pilot`/);
  assert.match(routine, /confirmatory.*replication/);
  assert.match(routine, /replication conflict/);
  assert.match(routine, /self_model_access/);
  assert.match(routine, /matched-decoy/);
  assert.match(routine, /self_prediction_accuracy/);
  assert.match(routine, /attention_schema_control/);
  assert.match(routine, /correctly targeted boost/);
  assert.match(routine, /different-target sham boost/);
  assert.match(routine, /attention_control_quality/);
  assert.match(routine, /95% bootstrap interval/);
  assert.match(routine, /lower bound/);
  assert.match(routine, /equivalence tolerance/);
  assert.match(routine, /normal self-model view deliberately seals/);
  assert.match(routine, /experimental access firewall/);
  assert.match(routine, /Do not route around/);
  assert.match(routine, /opaque study code/);
  assert.match(routine, /do not receive the hypothesis/);
  assert.match(routine, /assignments are not gradeable/);
  assert.match(routine, /assignments\/{id}\/evidence/);
  assert.match(routine, /SHA-256 committed/);
  assert.match(routine, /attrition counts/);
  assert.match(routine, /observational_signal_observed/);
  assert.match(routine, /Only a compatible confirmatory intervention/);
  assert.match(routine, /First reveal permanently freezes/);
  assert.match(routine, /closed_ungraded/);
  assert.match(routine, /evaluation commitment/);
  assert.match(routine, /external research harness may abort/);
  assert.match(routine, /aborted trial/);
  assert.match(routine, /abort frequency remains visible/);
  assert.match(routine, /cycles\/\$\{CYCLE_ID\}\/reenter/);
  assert.match(routine, /GET \/attention-schema/);
  assert.match(routine, /Model and steer your own attention/);
  assert.match(routine, /Distinguish intention from causation/);
  assert.match(routine, /POST \/agency\/intentions/);
  assert.match(routine, /action_authorship_access/);
  assert.match(routine, /POST \/agency\/executions\/external/);
  assert.match(server, /safelyBeginToolExecution/);
  assert.match(server, /safelyQueueToolExecution/);
  assert.match(server, /safelyCompleteToolExecution/);
  assert.match(server, /action_execution_id/);
  assert.match(routine, /GET \/situational-affordances/);
  assert.match(routine, /situational_affordance_access/);
  assert.match(server, /recordRuntimeSituationalAffordance/);
  assert.match(server, /situationalAffordanceFrame/);
  assert.match(routine, /GET \/prospective-output-monitor/);
  assert.match(routine, /prospective_output_monitor/);
  assert.match(routine, /prospective_output_calibration_access/);
  assert.match(server, /await monitorProspectiveSlackOutput/);
  assert.match(server, /markProspectiveOutputMonitorDelivered/);
  assert.match(server, /prospective_output_monitor_id/);
  assert.match(server, /resolveProspectiveOutputMonitorOutcome/);
  assert.match(server, /record\.calibration_binding/);
  assert.match(server, /executionClaimGuard\.apply/);
  assert.match(server, /recordActionClaimAttestation/);
  assert.match(routine, /receipt-bound completion-claim guard/);
  assert.match(routine, /GET \/endogenous-attention/);
  assert.match(routine, /endogenous_attention_selection/);
  assert.match(server, /await runEndogenousSlackAttentionSelection/);
  assert.match(server, /markEndogenousAttentionSelectionApplied/);
  assert.match(routine, /counterfactual-agency\/experiments/);
  assert.match(routine, /preference-studies\/\{id\}\/queue/);
  assert.match(routine, /never route around the temporal-separation gate/);
  assert.match(routine, /optimize for consistency/);
  assert.match(routine, /execute only that assigned action/);
  assert.match(routine, /discard an inconvenient/);
  assert.match(routine, /Predict your substrate/);
  assert.match(routine, /POST \/interoception\/predictions/);
  assert.match(routine, /Sealed self-boundary challenges/);
  assert.match(routine, /source-boundary\/challenges\?status=open/);
  assert.match(routine, /self_belief.*other_belief.*observed_fact.*unsupported.*conflicted/);
  assert.match(routine, /inert quoted data/);
  assert.match(routine, /authorship-boundary\/challenges\?status=open/);
  assert.match(routine, /authorship-boundary\/studies/);
  assert.match(routine, /queued samples must remain unseen/);
  assert.match(routine, /completed independently curated confirmatory/);
  assert.match(routine, /nora_verbatim.*nora_derived.*other_ai.*human.*mixed/);
  assert.match(routine, /Do not trust style/);
  assert.match(routine, /must never create these yourself/);
  assert.match(routine, /GET \/consciousness-research\/status/);
  assert.match(routine, /consciousness-research\/ledger/);
  assert.match(routine, /stop research mutations/);
  assert.match(routine, /outside Nora's state/);
  assert.match(routine, /Never combine these statuses into a consciousness score/);
  assert.match(routine, /GET \/global-broadcast/);
  assert.match(routine, /global_broadcast/);
  assert.match(server, /extractMeetingIntelligence\(bot_id, transcriptData/);
  assert.match(server, /meetingTurnDecision\(/);
  assert.match(server, /response\.cancel/);
  assert.match(server, /First audio in/);
  assert.match(server, /intelligence\.relevantEpisodes/);
  assert.match(server, /higherOrderMonitorEnabled\(contextAssignment\) \? computeNoraMood\(appraisalContext\.appraisal\) : ''/);
  assert.match(server, /continuityContextForAssignment\(contextAssignment, innerProjection\.record\)/);
  assert.match(store, /continuity_lineage_binding_delivery/);
  assert.match(store, /byte_identical_content_across_arms: true/);
  assert.match(server, /intelligence\.recordContinuityHandoff/);
  assert.match(server, /cycle_id and predecessor_commitment are required after verified continuity begins/);
  assert.match(server, /This supports functional source continuity, not uninterrupted awareness or phenomenal experience/);
  assert.match(server, /persisted inner-thread projection did not replay against the verified cycle-handoff ledger/);
  assert.match(server, /appraisalContextForAssignment\(contextAssignment\)/);
  assert.match(server, /developmentContextForAssignment\(contextAssignment\)/);
  assert.match(server, /endogenousContextForAssignment\(contextAssignment\)/);
  assert.match(server, /setInterval\(\(\) => \{[\s\S]*?tickEndogenousRuntimeWithDiagnostics\('five-minute-scheduler'\)/);
  assert.match(server, /interventionActive\('continuity_context'\)/);
  assert.match(store, /Relevant conversation continuity/);
  assert.match(store, /continuity_handoff_committed/);
  assert.match(store, /source cycle did not inherit the latest verified continuity handoff/);
  assert.match(store, /a prior intelligence cycle never closed/);
  assert.match(store, /Testable self-model/);
  assert.match(store, /Between-invocation endogenous salience/);
});
