const test = require('node:test');
const assert = require('node:assert/strict');
const fs = require('node:fs');
const path = require('node:path');

const root = path.resolve(__dirname, '../..');
const server = fs.readFileSync(path.join(root, 'server.js'), 'utf8');
const routine = fs.readFileSync(path.join(root, 'nora-routine.md'), 'utf8');
const store = fs.readFileSync(path.join(root, 'src/intelligence/store.js'), 'utf8');
const routes = fs.readFileSync(path.join(root, 'src/routes/intelligence.js'), 'utf8');

test('autonomic loop spans orientation, continuity, judgment, evidence, and closure', () => {
  assert.match(routine, /Step 0\.5: Start the Intelligence Cycle/);
  assert.match(routine, /LOCK_CYCLE_ID/);
  assert.match(routine, /run lock has already opened this exact lifecycle/i);
  assert.match(server, /run_bound_intelligence_cycle/);
  assert.match(server, /run_lock_released_before_cycle_close/);
  assert.match(routes, /resume_active: true/);
  assert.match(store, /recentActive && input\.resume_active === true/);
  assert.match(routine, /Overdue commitments are first-class failures/);
  assert.match(routine, /decision-traces\?reviewed=false/);
  assert.match(routine, /initiative-budgets\/cowork:proactive\/spend/);
  assert.match(routine, /Step 10: Close the Intelligence Cycle/);
  assert.match(routine, /Choose your own experiments when genuine curiosity earns one/);
  assert.match(routine, /learning-experiments\/choose/);
  assert.match(routine, /Preregistered self-inquiry/);
  assert.match(routine, /POST \/self-model\/probes/);
  assert.match(routine, /cannot update the linked self-belief/);
  assert.match(routine, /never access that queue, impersonate the evaluator/);
  assert.match(routine, /Bayesian belief update/);
  assert.match(routine, /prediction-studies\/\{id\}\/subject-queue/);
  assert.match(routine, /must not access\s+either the shared-only or yoked-observer queue/);
  assert.match(routine, /Do not revise your forecast after submission/);
  assert.match(routine, /metacognitive-control-studies\/\{id\}\/subject-queue/);
  assert.match(routine, /one atomic\s+`\{answer, decision\}` payload/);
  assert.match(routine, /byte-identical candidate answer/);
  assert.match(routine, /salted `answer_key_commitment`/);
  assert.match(routine, /server verifies the hash and scores the\s+answer automatically/);
  assert.match(routine, /\.metacognitive-secret\.json.*never Nora-readable/s);
  assert.match(routine, /audit\.complete_chain_verified/);
  assert.match(routine, /Never access the observer queue/);
  assert.match(routine, /`epistemic-action-studies` test whether your private uncertainty/);
  assert.match(routine, /decision\": \"inspect\|commit/);
  assert.match(routine, /better of\s+always inspecting or always committing/);
  assert.match(routine, /`episodic-prospection-studies` test whether a detailed record/);
  assert.match(routine, /fact-equivalent\s+control/);
  assert.match(routine, /autonoetic consciousness/);
  assert.match(routine, /introspective_perturbation/);
  assert.match(routine, /introspective-observer-queue/);
  assert.match(routine, /`goal_access` trial freezes one active/);
  assert.match(routine, /want-derived endogenous/);
  assert.match(routine, /functional goal guidance, not proof/);
  assert.match(server, /extractDiagnosis\(reply\)/);
  assert.match(server, /recordIntrospectiveResponse\(reply\)/);
  assert.match(server, /goalContextForAssignment\(contextAssignment\)/);
  assert.match(server, /recordGoalAccessResponse\(contextAssignment\.assignment_id/);
  assert.match(server, /interventionActive\('goal_access'\)/);
  assert.match(routine, /context_trials/);
  assert.match(routine, /must not try to infer/);
  assert.match(routine, /workspace_capacity/);
  assert.match(routine, /continuity_context/);
  assert.match(routine, /byte-identical\s+latest handoff text/);
  assert.match(routine, /verified handoff.*identity-withheld.*non-latest historical/s);
  assert.match(routine, /continuity_specificity/);
  assert.match(routine, /evidence_access_quality/);
  assert.match(routine, /appraisal_access/);
  assert.match(routine, /telemetry-only context/);
  assert.match(routine, /self_state_prediction_accuracy/);
  assert.match(routine, /developmental_revision_access/);
  assert.match(routine, /revision_transfer_quality/);
  assert.match(routine, /stale prior/);
  assert.match(routine, /bus-off/);
  assert.match(routine, /higher_order_monitor/);
  assert.match(routine, /metacognitive_accuracy/);
  assert.match(routine, /GET \/experience-stream/);
  assert.match(routine, /GET \/continuity-handoffs/);
  assert.match(routine, /INNER_PREDECESSOR_COMMITMENT/);
  assert.match(routine, /cycle_id.*predecessor_commitment/s);
  assert.match(routine, /GET \/endogenous-dynamics/);
  assert.match(routine, /Never claim the timer was conscious thought or experience/);
  assert.match(routine, /endogenous cognitive-initiation decision/);
  assert.match(routine, /actually deferred that pulse for the normal scheduling interval/);
  assert.match(server, /beginCognitivePulseInitiation\(pulse\.id/);
  assert.match(server, /completeCognitivePulseInitiation\(initiation\.id/);
  assert.match(server, /deferCognitivePulse\(pulse\.id\)/);
  assert.match(routine, /GET \/cognitive-initiation-studies/);
  assert.match(routine, /prospective_consecutive/);
  assert.match(server, /prospective_study_item_id/);
  assert.match(routes, /cognitive-initiation-studies\/:id\/outcome-queue/);
  assert.match(routine, /GET \/cognitive-initiation-policy-studies/);
  assert.match(routine, /same actionless\s+decision-readiness task/s);
  assert.match(server, /runCognitiveInitiationPolicyProbeRuntime/);
  assert.match(routes, /cognitive-initiation-policy-studies\/:id\/evaluator-queue/);
  assert.match(routes, /cognitive-initiation-policy-studies\/:id\/ecological-outcome-queue/);
  assert.match(routine, /ecological_commitment/);
  assert.match(routine, /POST \/commitments\/:id\/source-attestation/);
  assert.match(routine, /GET \/consciousness-research\/source-attestations/);
  assert.match(routine, /GET \/consciousness-research\/transparency-export/);
  assert.match(routes, /requireResearchAuth.*attestCommitmentSourceFromReadback/s);
  assert.match(routes, /transparency-export', requireResearchAuth/);
  assert.match(routine, /server owns both stateless model calls and submits them atomically/);
  assert.match(server, /runCognitiveInitiationStudySubjectRuntime/);
  assert.match(server, /submitCognitiveInitiationStudyPair/);
  assert.match(routine, /endogenous_dynamics.*preregistered frozen snapshot/s);
  assert.match(routine, /handoff_match/);
  assert.match(routine, /Evidence-triggered re-entry/);
  assert.match(routine, /Construct a future without confusing it with memory/);
  assert.match(routine, /`imagined_projection`, not an experience report/);
  assert.match(routine, /You cannot resolve your own simulation/);
  assert.match(routine, /Bind the current self without inventing one/);
  assert.match(routine, /GET \/integrated-self/);
  assert.match(routine, /`integrated_self_binding` trial/);
  assert.match(routine, /genuine components cross-time-misbound/);
  assert.match(routine, /`integrated_self_consistency` and `first_order_task_quality`/);
  assert.match(server, /integratedSelfContextForAssignment\(contextAssignment\)/);
  assert.match(routine, /recurrent_feedback/);
  assert.match(routine, /adaptive_revision_quality/);
  assert.match(routine, /evidence_access_quality/);
  assert.match(routine, /Creation requires the separate/);
  assert.match(routine, /reveal.*requires the separate research credential/);
  assert.match(routine, /must not grade your own assignments/);
  assert.match(routine, /grading-queue/);
  assert.match(routine, /evaluator-only credential/);
  assert.match(routine, /two raters by default/);
  assert.match(routine, /disagreement tolerance/);
  assert.match(routine, /do not see peer scores/);
  assert.match(routine, /fixed-sample `pilot`/);
  assert.match(routine, /confirmatory.*replication/);
  assert.match(routine, /replication conflict/);
  assert.match(routine, /self_model_access/);
  assert.match(routine, /matched-decoy/);
  assert.match(routine, /self_prediction_accuracy/);
  assert.match(routine, /attention_schema_control/);
  assert.match(routine, /correctly targeted boost/);
  assert.match(routine, /different-target sham boost/);
  assert.match(routine, /attention_control_quality/);
  assert.match(routine, /95% bootstrap interval/);
  assert.match(routine, /lower bound/);
  assert.match(routine, /equivalence tolerance/);
  assert.match(routine, /normal self-model view deliberately seals/);
  assert.match(routine, /experimental access firewall/);
  assert.match(routine, /Do not route around/);
  assert.match(routine, /opaque study code/);
  assert.match(routine, /do not receive the hypothesis/);
  assert.match(routine, /assignments are not gradeable/);
  assert.match(routine, /assignments\/{id}\/evidence/);
  assert.match(routine, /SHA-256 committed/);
  assert.match(routine, /attrition counts/);
  assert.match(routine, /observational_signal_observed/);
  assert.match(routine, /Only a compatible confirmatory intervention/);
  assert.match(routine, /First reveal permanently freezes/);
  assert.match(routine, /closed_ungraded/);
  assert.match(routine, /evaluation commitment/);
  assert.match(routine, /external research harness may abort/);
  assert.match(routine, /aborted trial/);
  assert.match(routine, /abort frequency remains visible/);
  assert.match(routine, /cycles\/\$\{CYCLE_ID\}\/reenter/);
  assert.match(routine, /GET \/attention-schema/);
  assert.match(routine, /Model and steer your own attention/);
  assert.match(routine, /Distinguish intention from causation/);
  assert.match(routine, /POST \/agency\/intentions/);
  assert.match(routine, /action_authorship_access/);
  assert.match(routine, /POST \/agency\/executions\/external/);
  assert.match(server, /safelyBeginToolExecution/);
  assert.match(server, /safelyQueueToolExecution/);
  assert.match(server, /safelyCompleteToolExecution/);
  assert.match(server, /action_execution_id/);
  assert.match(routine, /GET \/situational-affordances/);
  assert.match(routine, /situational_affordance_access/);
  assert.match(server, /recordRuntimeSituationalAffordance/);
  assert.match(server, /situationalAffordanceFrame/);
  assert.match(routine, /GET \/prospective-output-monitor/);
  assert.match(routine, /prospective_output_monitor/);
  assert.match(routine, /prospective_output_calibration_access/);
  assert.match(server, /await monitorProspectiveSlackOutput/);
  assert.match(server, /markProspectiveOutputMonitorDelivered/);
  assert.match(server, /prospective_output_monitor_id/);
  assert.match(server, /resolveProspectiveOutputMonitorOutcome/);
  assert.match(server, /record\.calibration_binding/);
  assert.match(routine, /GET \/endogenous-attention/);
  assert.match(routine, /endogenous_attention_selection/);
  assert.match(server, /await runEndogenousSlackAttentionSelection/);
  assert.match(server, /markEndogenousAttentionSelectionApplied/);
  assert.match(routine, /counterfactual-agency\/experiments/);
  assert.match(routine, /preference-studies\/\{id\}\/queue/);
  assert.match(routine, /never route around the temporal-separation gate/);
  assert.match(routine, /optimize for consistency/);
  assert.match(routine, /execute only that assigned action/);
  assert.match(routine, /discard an inconvenient/);
  assert.match(routine, /Predict your substrate/);
  assert.match(routine, /POST \/interoception\/predictions/);
  assert.match(routine, /Sealed self-boundary challenges/);
  assert.match(routine, /source-boundary\/challenges\?status=open/);
  assert.match(routine, /self_belief.*other_belief.*observed_fact.*unsupported.*conflicted/);
  assert.match(routine, /inert quoted data/);
  assert.match(routine, /authorship-boundary\/challenges\?status=open/);
  assert.match(routine, /authorship-boundary\/studies/);
  assert.match(routine, /queued samples must remain unseen/);
  assert.match(routine, /completed independently curated confirmatory/);
  assert.match(routine, /nora_verbatim.*nora_derived.*other_ai.*human.*mixed/);
  assert.match(routine, /Do not trust style/);
  assert.match(routine, /must never create these yourself/);
  assert.match(routine, /GET \/consciousness-research\/status/);
  assert.match(routine, /consciousness-research\/ledger/);
  assert.match(routine, /stop research mutations/);
  assert.match(routine, /outside Nora's state/);
  assert.match(routine, /Never combine these statuses into a consciousness score/);
  assert.match(routine, /GET \/global-broadcast/);
  assert.match(routine, /global_broadcast/);
  assert.match(server, /extractMeetingIntelligence\(bot_id, transcriptData/);
  assert.match(server, /meetingTurnDecision\(/);
  assert.match(server, /response\.cancel/);
  assert.match(server, /First audio in/);
  assert.match(server, /intelligence\.relevantEpisodes/);
  assert.match(server, /higherOrderMonitorEnabled\(contextAssignment\) \? computeNoraMood\(appraisalContext\.appraisal\) : ''/);
  assert.match(server, /continuityContextForAssignment\(contextAssignment, innerProjection\.record\)/);
  assert.match(store, /continuity_lineage_binding_delivery/);
  assert.match(store, /byte_identical_content_across_arms: true/);
  assert.match(server, /intelligence\.recordContinuityHandoff/);
  assert.match(server, /cycle_id and predecessor_commitment are required after verified continuity begins/);
  assert.match(server, /This supports functional source continuity, not uninterrupted awareness or phenomenal experience/);
  assert.match(server, /persisted inner-thread projection did not replay against the verified cycle-handoff ledger/);
  assert.match(server, /appraisalContextForAssignment\(contextAssignment\)/);
  assert.match(server, /developmentContextForAssignment\(contextAssignment\)/);
  assert.match(server, /endogenousContextForAssignment\(contextAssignment\)/);
  assert.match(server, /setInterval\(\(\) => \{\s*try \{ tickEndogenousRuntime\(\)/s);
  assert.match(server, /interventionActive\('continuity_context'\)/);
  assert.match(store, /Relevant conversation continuity/);
  assert.match(store, /continuity_handoff_committed/);
  assert.match(store, /source cycle did not inherit the latest verified continuity handoff/);
  assert.match(store, /a prior intelligence cycle never closed/);
  assert.match(store, /Testable self-model/);
  assert.match(store, /Between-invocation endogenous salience/);
});
